<?php

/**
 * Demo Layout View
 *
 */

declare(strict_types=1);
?><!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Format -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <!-- Title -->
        <title><?php $this->insertPageTitle(); ?></title>

        <!-- Viewport -->
        <meta name="HandheldFriendly" content="true">
        <meta name="MobileOptimized"  content="width">
        <meta name="viewport"         content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scale=no">

        <!-- Page Description -->
        <meta name="description" content="<?php $this->insertMetaDescription(); ?>">

        <!-- Page Keywords -->
        <meta name="keywords" content="<?php $this->insertMetaKeywords(); ?>">

        <?php $this->insertMetaRobots(2); ?>

        <?php $this->insertResourceFiles(2); ?>
    </head>
    <body>
        <div id="banner-area">
            Banner
            <nav>
                <?php $this->app->responder->insertPartial('Pith\\Framework\\SharedInfrastructure\\DemoNavLinksPartialRoute'); ?>
            </nav>
        </div>
        <div id="content-area">
            <div id="plate">
                <div id="content">
                    <?php $this->app->responder->insertPageContent($this->content_route); ?>
                </div>

                <hr/>
            </div>
            <div id="footer">
                <?php $this->app->responder->insertPartial('Pith\\Framework\\SharedInfrastructure\\FooterRoute'); ?>
            </div>
        </div>

    </body>
</html>