<?php
/**
 * Jello View
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>
<h1>Jello</h1>
<div style="background-color: #ff0;">

    <h2>Jello View</h2>
    <p>
        <?php echo $a; ?>,
    </p>

    <?php $this->app->engine->insertPartial('Pith\ExampleAirshipPack\JelloPartialRoute'); ?>

    <p>
        <?php echo FOO; ?>
    </p>

</div>
<footer>
    Jello Footer
</footer>