<?php

/**
 * Login Form partial view
 * -----------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>





<!-- Login form section -->
<div data-section="shared-ui-login-form">
    <div data-section-item="section-content">

        <div data-section-item-type="center-glide">

            <form data-section-item-type="form" data-form-show-passwords="no" action="<?php echo SHARED_UI_LOGIN_FORM_ACTION_LINK; ?>" method="post">

                <!-- Username field -->
                <div data-section-item-type="field" data-section-item="username-field" data-display-as-valid="no">
                    <label for="shared-ui-login-form-username-field">Username</label>
                    <div data-section-item-type="left-glide"><i class="bi bi-person" data-section-item-type="field-icon"></i></div>
                    <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-right" data-show="no"></i></div>
                    <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                    <input type="text" id="shared-ui-login-form-username-field" data-section-item="username-input" autocomplete="username" placeholder="Username">
                </div>


                <!-- Password field -->
                <div data-section-item-type="field" data-section-item="password-field" data-display-as-valid="no">
                    <label for="shared-ui-login-form-password-field">Password</label>
                    <div data-section-item-type="left-glide"><i class="bi bi-key" data-section-item-type="field-icon"></i></div>
                    <div data-section-item-type="right-glide"><i class="bi bi-eye" data-section-item-type="field-icon-right" data-section-item-role="password-eye" data-shared-ui-click-event="shared-ui.login-form >>> on-password-eye-click"></i></div>
                    <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                    <input type="password" id="shared-ui-login-form-password-field" data-section-item="password-input" autocomplete="current-password" placeholder="Password">
                </div>


                <div data-section-item-type="field" data-section-item="action-row" data-display-as-valid="no">
                    <div style="text-align: right;">
                        <a data-section-item="forgot-password-link" data-shared-ui-click-event="shared-ui.login-form >>> forgot-password">Forgot Password?</a> &nbsp; &nbsp; &nbsp;
                        <div data-section-item-type="login-submit-button-div" class="aero-gel aero-gel-blurred" tabindex="0" data-shared-ui-click-event="shared-ui.login-form >>> submit">Login</div>
                    </div>
                </div>

            </form>
        </div>


    </div>
    <div data-section-item="section-loading" data-show="no">
        <div class="hoja" style="font-size:20pt;">Loading...</div>
    </div>
</div>
