<?php /** @noinspection PhpVariableNamingConventionInspection */

/**
 * Quotes View
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 * @noinspection PhpVariableNamingConventionInspection - Long variable names are ok
 */

declare(strict_types=1);
?>

<?php echo $version_text; ?>
<br/>
Copyright (c) <?php echo $copyright_years; ?>

<br/><br/>

<h3>Quotes</h3>
<?php $foreach_else = true; ?>
<?php foreach($quote_results as $quotes_row_index => $test_quote_row): ?>
    <?php
        $foreach_else       = false;
        $html_safe_quote_id = $this->escape->html( (string) $test_quote_row['quote_id'] );
        $html_safe_quote    = $this->escape->html( (string) $test_quote_row['quote'] );
    ?>
    <?php echo $html_safe_quote_id; ?>
    <i>
        <?php echo $html_safe_quote; ?>
    </i>
    <br/>
<?php endforeach; ?>
<?php if($foreach_else): ?>
    <i>No test quotes found.</i> <br/>
<?php endif; ?>