<?php

    /**
     * Jello Layout View
     *
     */

    declare(strict_types=1);

    header('Content-Type: text/html; charset=utf-8');
?><!DOCTYPE html>
<html lang="en">
<head>
    <!-- Format -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!-- Title -->
    <title>Jello</title>

    <!-- Viewport -->
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized"  content="width">
    <meta name="viewport"         content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scale=no">

    <script src="/library/foo/foo.js"></script>
</head>
<body>
    <div>
        <?php $this->app->responder->insertPageContent($this->content_route); ?>
    </div>
</body>
</html>