<?php

/**
 * Green Layout View
 *
 */

declare(strict_types=1);
?><!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Format -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <!-- Title -->
        <title>Jello</title>

        <!-- Viewport -->
        <meta name="HandheldFriendly" content="true">
        <meta name="MobileOptimized"  content="width">
        <meta name="viewport"         content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scale=no">

        <?php $this->app->responder->insertResourceFiles(2); ?>
    </head>
    <body>
        <div id="banner-area">
            Banner
        </div>
        <div id="content-area">
            <div id="plate">
                <div id="content">
                    <?php $this->app->responder->insertPageContent($this->content_route); ?>
                </div>

                <hr/>

                <div id="bottom-quote">
                    <?php $this->app->responder->insertPartial('Pith\\Framework\\Test\\TestPage\\TestPageThree\\GreenLayoutExample\\BottomQuoteRoute'); ?>
                </div>
            </div>
            <div id="footer">
                <?php $this->app->responder->insertPartial('Pith\\Framework\\Test\\TestPage\\TestPageThree\\GreenLayoutExample\\FooterRoute'); ?>
            </div>
        </div>

    </body>
</html>