
<section>
    <h3>
        Show that included fonts are working:
    </h3>

    <ul>
        <li style="font-family: 'Anuphan Variable', sans-serif; font-weight: normal;">
            Anuphan Variable Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Anuphan Variable Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Anuphan Variable Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'IBM Plex Sans Light', sans-serif; font-weight: normal;">
            IBM Plex Sans Light (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Light (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Light (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'IBM Plex Sans', sans-serif; font-weight: normal;">
            IBM Plex Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'IBM Plex Sans Condensed', sans-serif; font-weight: normal;">
            IBM Plex Sans Condensed Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Condensed Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Condensed Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Iosevka Web', sans-serif; font-weight: normal;">
            Iosevka Web Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Iosevka Web Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Iosevka Web Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Iosevka VardanPro Term', sans-serif; font-weight: normal;">
            Iosevka VardanPro Term Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Iosevka VardanPro Term Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Iosevka VardanPro Term Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Iosevka VardanPro Term Lucida-style', sans-serif; font-weight: normal;">
            Iosevka VardanPro Term Lucida-style Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Iosevka VardanPro Term Lucida-style Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Iosevka VardanPro Term Lucida-style Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Iosevka VardanPro Term Monaco-style', sans-serif; font-weight: normal;">
            Iosevka VardanPro Term Monaco-style Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Iosevka VardanPro Term Monaco-style Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Iosevka VardanPro Term Monaco-style Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Iosevka VardanPro Term Ubuntu-style', sans-serif; font-weight: normal;">
            Iosevka VardanPro Term Ubuntu-style Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Iosevka VardanPro Term Ubuntu-style Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Iosevka VardanPro Term Ubuntu-style Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'JetBrains Mono NL', sans-serif; font-weight: normal; color:#00884b">
            JetBrains Mono NL. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            JetBrains Mono NL (italic). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i> <br/>
            JetBrains Mono NL (bold). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            JetBrains Mono NL (bold-italic).  <b><i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i></b>
        </li>

        <li style="font-family: 'Liberation Mono', sans-serif; font-weight: normal;">
            Liberation Mono Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Liberation Mono Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Liberation Mono Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Liberation Sans', sans-serif; font-weight: normal;">
            Liberation Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Liberation Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Liberation Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Liberation Serif', sans-serif; font-weight: normal;">
            Liberation Serif Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Liberation Serif Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Liberation Serif Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>


        <li style="font-family: 'Merriweather', sans-serif; font-weight: normal;">
            Merriweather Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Merriweather Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Merriweather Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>


        <li style="font-family: 'MesloLGS', sans-serif; font-weight: normal;">
            MesloLGS Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            MesloLGS Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            MesloLGS Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Monda', sans-serif; font-weight: normal;">
            Monda Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Monda Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Monda Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>



        <li style="font-family: 'Noto Sans Light', sans-serif; font-weight: normal;">
            Noto Sans Light (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Light (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Light (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Noto Sans Regular', sans-serif; font-weight: normal;">
            Noto Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Noto Sans Variable', sans-serif; font-weight: normal;">
            Noto Sans Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Noto Sans Mono Variable', sans-serif; font-weight: normal;">
            Noto Sans Mono Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Mono Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Mono Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>


        <li style="font-family: 'Open Sans Regular', sans-serif; font-weight: normal;">
            Open Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Variable', sans-serif; font-weight: normal;">
            Open Sans Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Italic Variable', sans-serif; font-weight: normal;">
            Open Sans Italic Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Italic Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Italic Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans', sans-serif; font-weight: normal;">
            Open Sans v34 (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans v34 (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans v34 (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Roboto', sans-serif; font-weight: normal;">
            Roboto Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Roboto Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Roboto Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Ubuntu', sans-serif; font-weight: normal;">
            Ubuntu Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Ubuntu Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Ubuntu Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Ubuntu Mono', sans-serif; font-weight: normal;">
            Ubuntu Mono Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Ubuntu Mono Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Ubuntu Mono Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
    </ul>
</section>