<?php

/**
 * Demo Nav Links View
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>

<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>">Home</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/lorem-ipsum">Lorem Ipsum</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration">Front-End Integration</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/quotes">Quotes</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/latte">Latte</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/test-email">Email</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/new-user">New User</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/new-user-2">New User 2</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/login">Login</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/login-2">Login 2</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-access-levels">Access Control</a>