<?php

/**
 * New User Signup Form partial view
 * ---------------------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>





<!-- New User Sign-up form section -->
<div data-section="shared-ui-new-user-signup-form">


    <div data-section-item-type="center-glide">
        <div data-section-item-type="form" data-form-show-passwords="no">

            <!-- Username field -->
            <div data-section-item-type="field" data-section-item="username-field" data-display-as-valid="no">
                <label for="shared-ui-new-user-signup-form-username-field">Username for Login</label>
                <div data-section-item-type="left-glide"><i class="bi bi-person" data-section-item-type="field-icon"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-right" data-show="no"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                <div data-section-item-type="right-glide">
                    <div data-section-item-type="field-callout-roller">
                        <div data-section-item-type="field-callout" data-show="no">
                            <div data-section-item-type="field-callout-gutter" class="aero-gel-shimmer aero-gel-blurred"><i class="bi bi-chevron-left"></i></div>
                            <span data-section-item-type="callout-content">
                                <ul>
                                    <li>Usernames for logging-in can contain <b>letters</b>, <b>numbers</b>, and <b>underscores</b>.</li>
                                    <li>Can start with a letter.</li>
                                    <li>Can end with a letter or a number.</li>
                                    <li>Only one underscore in a row.</li>
                                    <li>Allowed characters:
                                        <span data-section-item-type="callout-allowed-chars-list">
                                            abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789
                                        </span>
                                    </li>
                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
                <input type="text" id="shared-ui-new-user-signup-form-username-field" placeholder="Username" onkeyup="SharedUI.InputMaskUtility.username_mask(this);" data-shared-ui-focus-event="shared-ui.new-user-signup-form >>> on-field-focus" data-shared-ui-blur-event="shared-ui.new-user-signup-form >>> on-field-blur">
            </div>

            <!-- Email Address field -->
            <div data-section-item-type="field" data-section-item="email-address-field" data-display-as-valid="no">
                <label for="shared-ui-new-user-signup-form-email-address-field">Email Address</label>
                <div data-section-item-type="left-glide"><i class="bi bi-envelope-at" data-section-item-type="field-icon"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-right" data-show="no"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                <div data-section-item-type="right-glide">
                    <div data-section-item-type="field-callout-roller">
                        <div data-section-item-type="field-callout" data-show="no">
                            <div data-section-item-type="field-callout-gutter" class="aero-gel-shimmer aero-gel-blurred"><i class="bi bi-chevron-left"></i></div>
                            <span data-section-item-type="callout-content">
                                <ul>
                                    <li>Email address must be in normal format, <nbsp>i.e.</nbsp> <i><nbsp>name@example.com</nbsp></i></li>
                                    <li>Back-up email addresses can be added to account later.</li>
                                    <li>Can select option to log in with an email address after email address is verified.</li>

                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
                <input type="text" id="shared-ui-new-user-signup-form-email-address-field" placeholder="Email Address" data-shared-ui-focus-event="shared-ui.new-user-signup-form >>> on-field-focus" data-shared-ui-blur-event="shared-ui.new-user-signup-form >>> on-field-blur" data-shared-ui-input-event="shared-ui.new-user-signup-form >>> on-email-address-field-input">
            </div>

            <!-- Date-of-Birth field -->
            <div data-section-item-type="field" data-section-item="date-of-birth-field" data-display-as-valid="no">
                <label for="shared-ui-new-user-signup-form-dob-field">Birthday</label>
                <div data-section-item-type="left-glide"><i class="bi bi-gift" data-section-item-type="field-icon"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-right" data-show="no"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                <div data-section-item-type="right-glide">
                    <div data-section-item-type="field-callout-roller">
                        <div data-section-item-type="field-callout" data-show="no">
                            <div data-section-item-type="field-callout-gutter" class="aero-gel-shimmer aero-gel-blurred"><i class="bi bi-chevron-left"></i></div>
                            <span data-section-item-type="callout-content">
                                <ul>
                                    <li>Use <b><nbsp>MM/DD/YYYY</nbsp></b> as the date format.</li>
                                    <li>Date-of-birth is needed for us to follow legal requirements and age restrictions in various countries across the world.</li>
                                    <li>The calendar year of the user's <nbsp>date-of-birth</nbsp> must be at least 19 years before the current calendar year, <nbsp>i.e.</nbsp> <?php echo $year_19_years_ago ?> or earlier.</li>
                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
                <input type="text" id="shared-ui-new-user-signup-form-dob-field" placeholder="Date of Birth (MM/DD/YYYY)" onkeyup="SharedUI.InputMaskUtility.date_mmddyyyy_mask(this, event);" data-shared-ui-focus-event="shared-ui.new-user-signup-form >>> on-field-focus" data-shared-ui-blur-event="shared-ui.new-user-signup-form >>> on-field-blur">
            </div>

            <!-- Password field -->
            <div data-section-item-type="field" data-section-item="password-field" data-display-as-valid="no">
                <label for="shared-ui-new-user-signup-form-password-field">New Password</label>
                <div data-section-item-type="left-glide"><i class="bi bi-key" data-section-item-type="field-icon"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-eye" data-section-item-type="field-icon-right" data-section-item-role="password-eye" data-shared-ui-click-event="shared-ui.new-user-signup-form >>> on-password-eye-click"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                <div data-section-item-type="right-glide">
                    <div data-section-item-type="field-callout-roller">
                        <div data-section-item-type="field-callout" data-show="no">
                            <div data-section-item-type="field-callout-gutter" class="aero-gel-shimmer aero-gel-blurred"><i class="bi bi-chevron-left"></i></div>
                            <span data-section-item-type="callout-content">
                                <ul>
                                    <li>Password must be 10 characters or longer.</li>
                                    <li>Password cannot contain any spaces, tabs, or commas.</li>
                                    <li>Please use a good password!</li>
                                    <li>See also: <a href="https://xkcd.com/936/" target="_blank">xkcd.com/936/</a></li>
                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
                <input type="password" id="shared-ui-new-user-signup-form-password-field" data-section-item="password-input" autocomplete="new-password" placeholder="Password" data-shared-ui-focus-event="shared-ui.new-user-signup-form >>> on-field-focus" data-shared-ui-blur-event="shared-ui.new-user-signup-form >>> on-field-blur">
            </div>

            <!-- Confirm Password field -->
            <div data-section-item-type="field" data-section-item="confirm-password-field" data-display-as-valid="no">
                <label for="shared-ui-new-user-signup-form-confirm-password-field">Confirm New Password</label>
                <div data-section-item-type="left-glide"><i class="bi bi-key" data-section-item-type="field-icon"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-eye" data-section-item-type="field-icon-right" data-section-item-role="password-eye" data-shared-ui-click-event="shared-ui.new-user-signup-form >>> on-password-eye-click"></i></div>
                <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                <div data-section-item-type="right-glide">
                    <div data-section-item-type="field-callout-roller">
                        <div data-section-item-type="field-callout" data-show="no">
                            <div data-section-item-type="field-callout-gutter" class="aero-gel-shimmer aero-gel-blurred"><i class="bi bi-chevron-left"></i></div>
                            <span data-section-item-type="callout-content">
                                <ul>
                                    <li>Must match password.</li>
                                </ul>
                            </span>
                        </div>
                    </div>
                </div>
                <input type="password" id="shared-ui-new-user-signup-form-confirm-password-field" data-section-item="confirm-password-input" autocomplete="new-password" placeholder="Confirm Password" data-shared-ui-focus-event="shared-ui.new-user-signup-form >>> on-field-focus" data-shared-ui-blur-event="shared-ui.new-user-signup-form >>> on-field-blur">
            </div>
        </div>
    </div>

    <div data-section-item-type="center-glide">
        <div data-item-type="signup-submit-button-div" class="aero-gel aero-gel-blurred" tabindex="0">Continue </div>
    </div>

</div>

<hr/>

<i data-item-role="field-text-visibility-icon" data-when-text-visibility="hidden"  data-show="yes" class="fa-solid fa-eye"></i>
<i data-item-role="field-text-visibility-icon" data-when-text-visibility="visible" data-show="no"  class="fa-regular fa-eye-slash"></i>
<i data-item-role="field-validity-icon" data-when-validity="valid"   data-show="no" class="fa4 fa4-check-circle-o" aria-hidden="true"></i>
<i data-item-role="field-validity-icon" data-when-validity="invalid" data-show="no" class="fa4 fa4-times-circle-o" aria-hidden="true"></i>

<hr/>

<i class="fa-solid fa-user"></i>
<i class="fa-regular fa-user"></i>

<i class="fa-solid fa-address-card"></i>
<i class="fa-regular fa-address-card"></i>
<i class="fa-solid fa-id-card"></i>
<i class="fa-regular fa-id-card"></i>

<i class="fa-solid fa-envelope"></i>
<i class="fa-regular fa-envelope"></i>

<i class="fa-solid fa-lock"></i>
<i class="fa-solid fa-check"></i>
<i class="fa-regular fa-circle-check"></i>

<i class="fa-solid fa-xmark"></i>
<i class="fa-regular fa-circle-xmark"></i>

<i class="fa-solid fa-key"></i>

<i class="fa-solid fa-asterisk"></i>

<hr/>

<i class="fa4 fa4-id-card" aria-hidden="true"></i>
<i class="fa4 fa4-id-card-o" aria-hidden="true"></i>

<i class="fa4 fa4-lock" aria-hidden="true"></i>

<i class="fa4 fa4-check" aria-hidden="true"></i>
<i class="fa4 fa4-times" aria-hidden="true"></i>

<i class="fa4 fa4-spinner fa4-pulse"></i>


<hr/>
<i class="bi bi-person"></i>
<i class="bi bi-person-fill"></i>
<i class="bi bi-person-vcard"></i>
<i class="bi bi-person-vcard-fill"></i>
<i class="bi bi-envelope"></i>
<i class="bi bi-envelope-fill"></i>
<i class="bi bi-envelope-at"></i>
<i class="bi bi-envelope-at-fill"></i>
<i class="bi bi-lock"></i>
<i class="bi bi-lock-fill"></i>
<i class="bi bi-eye"></i>
<i class="bi bi-eye-fill"></i>
<i class="bi bi-eye-slash"></i>
<i class="bi bi-eye-slash-fill"></i>
<i class="bi bi-asterisk"></i>
<i class="bi bi-check"></i>
<i class="bi bi-check-lg"></i>
<i class="bi bi-check2"></i>
<i class="bi bi-check2-circle"></i>
<i class="bi bi-key"></i>
<i class="bi bi-key-fill"></i>
<i class="bi bi-x-lg"></i>
<i class="bi bi-x-octagon"></i>
<i class="bi bi-triangle"></i>
<i class="bi bi-triangle-fill"></i>
<i class="bi bi-exclamation-triangle"></i>
<i class="bi bi-exclamation-triangle-fill"></i>
<i class="bi bi-exclamation-diamond"></i>
<i class="bi bi-exclamation-diamond-fill"></i>
<i class="bi bi-slash-circle"></i>
<i class="bi bi-gift"></i>
<i class="bi bi-gift-fill"></i>
<i class="bi bi-braces-asterisk"></i>
<i class="bi bi-type"></i>
<i class="bi bi-chevron-right"></i>
