<?php

/**
 * New User Signup Form partial view
 * ---------------------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>






<div data-section="shared-ui-new-user-signup-form">


    <div data-section-item-type="center-glide">
        <div data-section-item-type="form">
            <div data-section-item-type="field">
                <label for="shared-ui-new-user-signup-form-username-field">Username for Login</label>
                <div data-section-item-type="left-glide"><i class="bi bi-person" data-section-item-type="field-icon"></i></div>
                <input type="text" id="shared-ui-new-user-signup-form-username-field" placeholder="Username" onkeyup="SharedUI.InputMaskUtility.username_mask(this);">
            </div>

            <div data-section-item-type="field">
                <label for="shared-ui-new-user-signup-form-email-address-field">Email Address</label>
                <div data-section-item-type="left-glide"><i class="bi bi-envelope-at" data-section-item-type="field-icon"></i></div>
                <input type="text" id="shared-ui-new-user-signup-form-email-address-field" placeholder="Email Address">
            </div>

            <div data-section-item-type="field">
                <label for="shared-ui-new-user-signup-form-dob-field">Birthday</label>
                <div data-section-item-type="left-glide"><i class="bi bi-gift" data-section-item-type="field-icon"></i></div>
                <input type="text" id="shared-ui-new-user-signup-form-dob-field" placeholder="Date of Birth (MM/DD/YYYY)" onkeyup="SharedUI.InputMaskUtility.date_mmddyyyy_mask(this, event);">
            </div>

            <div data-section-item-type="field">
                <label for="shared-ui-new-user-signup-form-password-field">New Password</label>
                <div data-section-item-type="left-glide"><i class="bi bi-key" data-section-item-type="field-icon"></i></div>
                <input type="password" id="shared-ui-new-user-signup-form-password-field" autocomplete="new-password" placeholder="Password">
            </div>

            <div data-section-item-type="field">
                <label for="shared-ui-new-user-signup-form-confirm-password-field">Confirm New Password</label>
                <div data-section-item-type="left-glide"><i class="bi bi-key" data-section-item-type="field-icon"></i></div>
                <input type="password" id="shared-ui-new-user-signup-form-confirm-password-field" autocomplete="new-password" placeholder="Confirm Password">
            </div>
        </div>
    </div>

    <div data-section-item-type="center-glide">
        <div data-item-type="signup-submit-button-div" class="aero-gel aero-gel-blurred">Continue </div>
    </div>

</div>

<hr/>

<i data-item-role="field-text-visibility-icon" data-when-text-visibility="hidden"  data-show="yes" class="fa-solid fa-eye"></i>
<i data-item-role="field-text-visibility-icon" data-when-text-visibility="visible" data-show="no"  class="fa-regular fa-eye-slash"></i>
<i data-item-role="field-validity-icon" data-when-validity="valid"   data-show="no" class="fa4 fa4-check-circle-o" aria-hidden="true"></i>
<i data-item-role="field-validity-icon" data-when-validity="invalid" data-show="no" class="fa4 fa4-times-circle-o" aria-hidden="true"></i>

<hr/>

<i class="fa-solid fa-user"></i>
<i class="fa-regular fa-user"></i>

<i class="fa-solid fa-address-card"></i>
<i class="fa-regular fa-address-card"></i>
<i class="fa-solid fa-id-card"></i>
<i class="fa-regular fa-id-card"></i>

<i class="fa-solid fa-envelope"></i>
<i class="fa-regular fa-envelope"></i>

<i class="fa-solid fa-lock"></i>
<i class="fa-solid fa-check"></i>
<i class="fa-regular fa-circle-check"></i>

<i class="fa-solid fa-xmark"></i>
<i class="fa-regular fa-circle-xmark"></i>

<i class="fa-solid fa-key"></i>

<i class="fa-solid fa-asterisk"></i>

<hr/>

<i class="fa4 fa4-id-card" aria-hidden="true"></i>
<i class="fa4 fa4-id-card-o" aria-hidden="true"></i>

<i class="fa4 fa4-lock" aria-hidden="true"></i>

<i class="fa4 fa4-check" aria-hidden="true"></i>
<i class="fa4 fa4-times" aria-hidden="true"></i>

<i class="fa4 fa4-spinner fa4-pulse"></i>


<hr/>
<i class="bi bi-person"></i>
<i class="bi bi-person-fill"></i>
<i class="bi bi-person-vcard"></i>
<i class="bi bi-person-vcard-fill"></i>
<i class="bi bi-envelope"></i>
<i class="bi bi-envelope-fill"></i>
<i class="bi bi-envelope-at"></i>
<i class="bi bi-envelope-at-fill"></i>
<i class="bi bi-lock"></i>
<i class="bi bi-lock-fill"></i>
<i class="bi bi-eye"></i>
<i class="bi bi-eye-fill"></i>
<i class="bi bi-eye-slash"></i>
<i class="bi bi-eye-slash-fill"></i>
<i class="bi bi-asterisk"></i>
<i class="bi bi-check"></i>
<i class="bi bi-check-lg"></i>
<i class="bi bi-check2"></i>
<i class="bi bi-check2-circle"></i>
<i class="bi bi-key"></i>
<i class="bi bi-key-fill"></i>
<i class="bi bi-x-lg"></i>
<i class="bi bi-x-octagon"></i>
<i class="bi bi-triangle"></i>
<i class="bi bi-triangle-fill"></i>
<i class="bi bi-exclamation-triangle"></i>
<i class="bi bi-exclamation-triangle-fill"></i>
<i class="bi bi-exclamation-diamond"></i>
<i class="bi bi-exclamation-diamond-fill"></i>
<i class="bi bi-slash-circle"></i>
<i class="bi bi-gift"></i>
<i class="bi bi-gift-fill"></i>
<i class="bi bi-braces-asterisk"></i>
<i class="bi bi-type"></i>
<i class="bi bi-chevron-right"></i>
