<?php

/**
 * Demonstrate libraries work View
 * -------------------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>

<!--suppress HtmlUnknownTarget -->
<section>
    <h3>Demonstrate that front-end libraries work:</h3>

    <ul>
        <li>
            <a href="/demonstrate-library/font-awesome-4">Font Awesome 4.7.0</a>
        </li>
        <li>
            <a href="/demonstrate-library/font-awesome-4-compatibility-fork">Font Awesome 4.7.0 compatibility fork</a>
        </li>
        <li>
            <a href="/demonstrate-library/oxcss">OxCSS 0.1.4</a>
        </li>
        <li>
            <a href="/demonstrate-library/swal-2-ng">Swal2 NG 11.7.3</a>
        </li>
        <li>
            <a href="/demonstrate-library/toastr">Toastr 2.1.4</a>
        </li>
    </ul>
</section>
