

Show that Bootstrap 5 is working:


<div class="d-flex gap-2 justify-content-center py-5">
    <button class="btn btn-primary d-inline-flex align-items-center" type="button">
        Primary icon
        <i class="bi-arrow-right-short" style="font-size: 2em;"></i>
    </button>
    <button class="btn btn-outline-secondary d-inline-flex align-items-center" type="button">
        Secondary icon
        <i class="bi-arrow-right-short" style="font-size: 2em;"></i>
    </button>
</div>


<div class="d-flex gap-2 justify-content-center py-5">
    <i class="bi-arrow-right-short" style="font-size: 3em;"></i>
    <i class="bi-heart-fill" style="font-size: 3em;"></i>
    <i class="bi-toggles" style="font-size: 3em;"></i>
    <i class="bi-shop" style="font-size: 3em;"></i>
</div>