
<section>
    <h3>
        Show that included fonts are working:
    </h3>

    <ul>
        <li style="font-family: 'JetBrains Mono NL', sans-serif;">
            JetBrains Mono NL Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>
        <li style="font-family: 'Meslo LG S', sans-serif;">
            Meslo LG S Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>

        <li style="font-family: 'Monda', sans-serif;">
            Monda Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>

        <li style="font-family: 'Noto Sans Light', sans-serif;">
            Noto Sans Light. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>

        <li style="font-family: 'Noto Sans', sans-serif;">
            Noto Sans Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>

        <li style="font-family: 'Open Sans', sans-serif;">
            Open Sans Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>

        <li style="font-family: 'Roboto', sans-serif;">
            Roboto Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>

        <li style="font-family: 'Ubuntu', sans-serif;">
            Ubuntu Regular. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789
        </li>
    </ul>
</section>