
Show that <i class="fa fa-flag" aria-hidden="true"></i> Font Awesome 4 is working:

<p>
    Show is 4.7.0:
    <i class="fa fa-ravelry" aria-hidden="true"></i>
    <i class="fa fa-bath" aria-hidden="true"></i>
    <i class="fa fa-address-card" aria-hidden="true"></i>
</p>

<p>
    OS
    <i class="fa fa-windows" aria-hidden="true"></i>
    <i class="fa fa-apple" aria-hidden="true"></i>
    <i class="fa fa-linux" aria-hidden="true"></i>

</p>


<p>
    Browsers
    <i class="fa fa-internet-explorer" aria-hidden="true"></i>
    <i class="fa fa-firefox" aria-hidden="true"></i>
    <i class="fa fa-chrome" aria-hidden="true"></i>
    <i class="fa fa-opera" aria-hidden="true"></i>
</p>

