
<section>
    <h3>
        Show that included fonts are working:
    </h3>

    <ul>
        <li style="font-family: 'IBM Plex Sans Light', sans-serif;">
            IBM Plex Sans Light (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Light (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Light (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'IBM Plex Sans', sans-serif;">
            IBM Plex Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'JetBrains Mono NL', sans-serif;">
            JetBrains Mono NL Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            JetBrains Mono NL Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            JetBrains Mono NL Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'MesloLGS', sans-serif;">
            MesloLGS Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            MesloLGS Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            MesloLGS Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Monda', sans-serif;">
            Monda Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Monda Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Monda Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Noto Sans Light', sans-serif;">
            Noto Sans Light (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Light (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Light (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Noto Sans', sans-serif;">
            Noto Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Regular', sans-serif;">
            Open Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Variable', sans-serif;">
            Open Sans Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Italic Variable', sans-serif;">
            Open Sans Italic Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Italic Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Italic Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans', sans-serif;">
            Open Sans v34 (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans v34 (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans v34 (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Roboto', sans-serif;">
            Roboto Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Roboto Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Roboto Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Ubuntu', sans-serif;">
            Ubuntu Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Ubuntu Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Ubuntu Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
    </ul>
</section>