

Show that <i class="fa4 fa4-flag" aria-hidden="true"></i> Font Awesome 4 compatibility fork is working:

<p>
    Show is 4.7.0:
    <i class="fa4 fa4-ravelry" aria-hidden="true"></i>
    <i class="fa4 fa4-bath" aria-hidden="true"></i>
    <i class="fa4 fa4-address-card" aria-hidden="true"></i>
</p>

<p>
    OS
    <i class="fa4 fa4-windows" aria-hidden="true"></i>
    <i class="fa4 fa4-apple" aria-hidden="true"></i>
    <i class="fa4 fa4-linux" aria-hidden="true"></i>
    
</p>


<p>
    Browsers
    <i class="fa4 fa4-internet-explorer" aria-hidden="true"></i>
    <i class="fa4 fa4-firefox" aria-hidden="true"></i>
    <i class="fa4 fa4-chrome" aria-hidden="true"></i>
    <i class="fa4 fa4-opera" aria-hidden="true"></i>
</p>

