<?php

/**
 * Demo Nav Links View
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>

<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>">Home</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/lorem-ipsum">Lorem Ipsum</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-libraries-work">Front-end Libraries</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/quotes">Quotes</a>
|
<a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/latte">Latte</a>