<?php
/**
 * Jello View
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>
<h1>Jello</h1>
<div style="background-color: #ff0;">

    <h2>Jello View</h2>
    <p>
        <?php echo $a; ?>
    </p>

    <?php $this->app->responder->insertPartial('\Pith\Framework\Test\TestPage\TestPageOne\YellowJelloPack\JelloPartialRoute'); ?>

    <p>
        <?php echo FOO; ?>
    </p>

    <p>
        <?php echo $version_text; ?>
    </p>

</div>
<footer>
    Jello Footer
</footer>