<?php

/**
 * Migration to create access levels table
 * ---------------------------------------
 *
 * @noinspection PhpUnused - Migration, used by migration tool.
 * @noinspection PhpClassNamingConventionInspection - Long class name is ok.
 * @noinspection PhpMissingParentCallCommonInspection - Parent calls not needed here.
 * @noinspection PhpMethodNamingConventionInspection - Short method names are ok.
 */

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20251119030748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_access_levels.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
        /** @lang PostgreSQL */
            'CREATE TABLE pith_access_levels (
                access_level_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                access_level_name TEXT UNIQUE NOT NULL
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pith_access_levels');
    }
}
