<?php

/**
 * Migration to create user access levels table
 * --------------------------------------------
 *
 * @noinspection PhpUnused - Migration, used by migration tool.
 * @noinspection PhpClassNamingConventionInspection - Long class name is ok.
 * @noinspection PhpMissingParentCallCommonInspection - Parent calls not needed here.
 * @noinspection PhpMethodNamingConventionInspection - Short method names are ok.
 */

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20251120053650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_user_access_levels.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
        /** @lang PostgreSQL */
            'CREATE TABLE pith_user_access_levels (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT DEFAULT NULL,
                    access_level_id INT DEFAULT NULL,
                    constraint fk_user_id
                        foreign key (user_id) 
                        REFERENCES pith_users (user_id)
                        ON DELETE SET NULL,
                    constraint fk_access_level_id
                        foreign key (access_level_id) 
                        REFERENCES pith_access_levels (access_level_id)
                        ON DELETE SET NULL
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pith_user_access_levels');
    }
}
