<?php

/**
 * Migration to create user table
 * ------------------------------
 *
 * @noinspection PhpClassNamingConventionInspection - Long class name for migration is ok.
 * @noinspection PhpMethodNamingConventionInspection - Short method names are ok.
 * @noinspection PhpUnused - Used by database migration tool
 * @noinspection PhpMissingParentCallCommonInspection - Meant to not call parent, for this use-case.
 */

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20251115051341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_users.';
    }

    public function up(Schema $schema): void
    {
        // Side Notes:
        // - Making `username` `username_lower` `primary_email_address` be "UNIQUE" but not "NOT NULL",
        //       because we'll be migrating to this from systems that rely on just email login,
        //       and also systems with usernames and non-unique emails addresses.

        $this->addSql(
            /** @lang PostgreSQL */
            'CREATE TABLE pith_users (
                user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_uuid7 uuid UNIQUE NOT NULL DEFAULT uuidv7(),
                postfix_chars CHAR(2) NOT NULL,
                username TEXT UNIQUE DEFAULT NULL,
                username_lower TEXT UNIQUE DEFAULT NULL,
                primary_email_address TEXT UNIQUE DEFAULT NULL,
                is_primary_email_address_validated BOOLEAN NOT NULL DEFAULT FALSE,
                password_hash TEXT NOT NULL,
                is_user_validated BOOLEAN NOT NULL DEFAULT FALSE,
                datetime_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                datetime_modified TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pith_users');
    }
}
