<?php

/**
 * Migration to add test_quotes table
 * ----------------------------------
 *
 * @noinspection PhpClassNamingConventionInspection - Long class name for migration is ok.
 * @noinspection PhpMethodNamingConventionInspection - Short method names are ok.
 * @noinspection PhpUnused - Used by database migration tool
 * @noinspection PhpMissingParentCallCommonInspection - Meant to not call parent, for this use-case.
 */

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20251112053749 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_test_quotes.';
    }

    public function up(Schema $schema): void
    {
        // This is the up() migration
        
        $this->addSql('
            CREATE TABLE pith_test_quotes (
                quote_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                quote TEXT DEFAULT NULL
            )'
        );
    }

    public function down(Schema $schema): void
    {
        // This is the down() migration

        $this->addSql('DROP TABLE pith_test_quotes');
    }
}
