<?php

/**
 * Migration to create user roles table
 * ------------------------------------
 *
 * @noinspection PhpUnused - Migration, used by migration tool.
 * @noinspection PhpClassNamingConventionInspection - Long class name is ok.
 * @noinspection PhpMissingParentCallCommonInspection - Parent calls not needed here.
 * @noinspection PhpMethodNamingConventionInspection - Short method names are ok.
 */

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20251116030343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_user_roles.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
                /** @lang PostgreSQL */
            'CREATE TABLE pith_user_roles (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT DEFAULT NULL,
                    role_id INT DEFAULT NULL,
                    constraint fk_user_id
                        foreign key (user_id) 
                        REFERENCES pith_users (user_id)
                        ON DELETE SET NULL,
                    constraint fk_role_id
                        foreign key (role_id) 
                        REFERENCES pith_roles (role_id)
                        ON DELETE SET NULL
            )'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pith_user_roles');
    }
}
