<?php

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251112053749 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_test_quotes.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        
        $this->addSql('
            CREATE TABLE pith_test_quotes (
                quote_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                quote TEXT DEFAULT NULL
            )'
        );
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs

        $this->addSql('DROP TABLE pith_test_quotes');
    }
}
