<?php

/**
 * Migration to create password reset tokens table
 * -----------------------------------------------
 *
 * @noinspection PhpUnused - Migration, used by migration tool.
 * @noinspection PhpClassNamingConventionInspection - Long class name is ok.
 * @noinspection PhpMissingParentCallCommonInspection - Parent calls not needed here.
 * @noinspection PhpMethodNamingConventionInspection - Short method names are ok.
 */

declare(strict_types=1);

namespace Pith\Framework\Migration;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration
 */
final class Version20260810000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create new table, pith_password_reset_tokens.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            /** @lang PostgreSQL */
            'CREATE TABLE pith_password_reset_tokens (
                token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                token_hash TEXT UNIQUE NOT NULL,
                expires_at TIMESTAMPTZ NOT NULL,
                used_at TIMESTAMPTZ DEFAULT NULL,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_password_reset_tokens_user_id
                    FOREIGN KEY (user_id)
                    REFERENCES pith_users (user_id)
                    ON DELETE CASCADE
            )'
        );

        $this->addSql(
            /** @lang PostgreSQL */
            'CREATE INDEX idx_password_reset_tokens_user_id ON pith_password_reset_tokens (user_id)'
        );

        $this->addSql(
            /** @lang PostgreSQL */
            'CREATE INDEX idx_password_reset_tokens_token_hash ON pith_password_reset_tokens (token_hash)'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS pith_password_reset_tokens');
    }
}
