<?php

/**
 * Forgot Password Form partial view
 * ---------------------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>





<!-- Forgot password form section -->
<div data-section="shared-ui-forgot-password-form">
    <div data-section-item="section-notification" data-show="no">
        <div data-section-item-type="center-glide">
            <div data-section-item="success-message-note" data-show="no">
                If an account exists for that email address, a password reset link has been sent.
            </div>
        </div>
    </div>
    <div data-section-item="section-content">

        <div data-section-item-type="center-glide">

            <form data-section-item-type="form" action="#" method="post" onsubmit="return false;">

                <!-- Email address field -->
                <div data-section-item-type="field" data-section-item="email-address-field" data-display-as-valid="no">
                    <label for="shared-ui-forgot-password-form-email-address-field">Email Address</label>
                    <div data-section-item-type="left-glide"><i class="bi bi-envelope" data-section-item-type="field-icon"></i></div>
                    <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-right" data-show="no"></i></div>
                    <div data-section-item-type="right-glide"><i class="bi bi-x-lg" data-section-item-type="field-icon-after" data-show="no"></i></div>
                    <input name="email_address" type="text" id="shared-ui-forgot-password-form-email-address-field" data-section-item="email-address-input" autocomplete="email" placeholder="Email Address">
                </div>


                <div data-section-item-type="field" data-section-item="action-row" data-display-as-valid="no">
                    <div style="text-align: right;">
                        <a data-section-item="back-to-login-link" href="<?php echo PITH_APP_DEFAULT_LOGIN_PAGE_URL_PATH; ?>">Back to Login</a> &nbsp; &nbsp; &nbsp;
                        <div data-section-item-type="forgot-password-submit-button-div" class="aero-gel aero-gel-blurred" tabindex="0" data-shared-ui-click-event="shared-ui.forgot-password-form >>> submit">Send Reset Link</div>
                    </div>
                </div>

            </form>
        </div>


    </div>
    <div data-section-item="section-loading" data-show="no">
        <div class="hoja" style="font-size:20pt;">Loading...</div>
    </div>
</div>
