<?php

/**
 * Demonstrate Access Levels View
 * -------------------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>
<!--suppress HtmlUnknownTarget -->
<section>
    <h3>Demonstrate Access-Levels:</h3>
    <ul>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-access-levels/user-access">User Access</a>
        </li>
    </ul>
</section>





