<?php

/**
 * Demonstrate libraries work View
 * -------------------------------
 *
 * @noinspection PhpUndefinedVariableInspection - Variables defined outside scope
 */

declare(strict_types=1);
?>

<!--suppress HtmlUnknownTarget -->
<section>

    <h3>Demonstrate that fonts work:</h3>
    <ul>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/demonstrate-fonts-work">Included Fonts</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/demonstrate-fontsheets">Fontsheets</a>
        </li>
    </ul>

    <h3>Demonstrate that front-end libraries work:</h3>

    <ul>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/animate-css">Animate.css 4.1.1</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/bootstrap-5">Bootstrap 5.3.0 alpha 3</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/font-awesome-4">Font Awesome 4.7.0</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/font-awesome-4-compatibility-fork">Font Awesome 4.7.0 compatibility fork</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/font-awesome-6-free">Font Awesome free 6.4.0 (web)</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/hoja">Hoja</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/hoja-aquamarine">Hoja Aquamarine</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/hoja-blue">Hoja Blue</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/jscrollpane">jScrollPane</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/oxcss">OxCSS 0.1.4</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/swal-2-na">Swal2 NA 11.7.3</a>
        </li>
        <li>
            <a href="<?php echo PITH_DEMO_PAGES_ROUTE_GROUP_PATH; ?>/demonstrate-front-end-integration/toastr">Toastr 2.1.4</a>
        </li>
    </ul>
</section>
