
<section>
    <h3>
        Show that included fonts are working:
    </h3>

    <ul>
        <li style="font-family: 'IBM Plex Sans Light', sans-serif; font-weight: normal;">
            IBM Plex Sans Light (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Light (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Light (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family:'IBM Plex Sans',Frutiger,'Segoe UI','Frutiger Linotype','Dejavu Sans','Helvetica Neue',Helvetica,Arial,sans-serif; font-weight: normal; color:#00884b">
            IBM Plex Sans. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans (italic). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i> <br/>
            IBM Plex Sans (bold). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans (bold-italic).  <b><i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i></b>
        </li>

        <li style="font-family: 'IBM Plex Sans Condensed', sans-serif; font-weight: normal;">
            IBM Plex Sans Condensed Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            IBM Plex Sans Condensed Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            IBM Plex Sans Condensed Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'JetBrains Mono NL', sans-serif; font-weight: normal; color:#00884b">
            JetBrains Mono NL. The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            JetBrains Mono NL (italic). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i> <br/>
            JetBrains Mono NL (bold). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            JetBrains Mono NL (bold-italic).  <b><i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i></b>
        </li>

        <li style="font-family: 'MesloLGS', sans-serif; font-weight: normal;">
            MesloLGS Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            MesloLGS Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            MesloLGS Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Monda', sans-serif; font-weight: normal;">
            Monda Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Monda Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Monda Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>



        <li style="font-family: 'Noto Sans Light', sans-serif; font-weight: normal;">
            Noto Sans Light (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Light (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Light (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Noto Sans Regular', sans-serif; font-weight: normal;">
            Noto Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Noto Sans Variable', sans-serif; font-weight: normal;">
            Noto Sans Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Noto Sans Mono Variable', sans-serif; font-weight: normal;">
            Noto Sans Mono Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Noto Sans Mono Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Noto Sans Mono Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>


        <li style="font-family: 'Open Sans Regular', sans-serif; font-weight: normal;">
            Open Sans Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Variable', sans-serif; font-weight: normal;">
            Open Sans Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans Italic Variable', sans-serif; font-weight: normal;">
            Open Sans Italic Variable (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans Italic Variable (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans Italic Variable (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Open Sans', sans-serif; font-weight: normal;">
            Open Sans v34 (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Open Sans v34 (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Open Sans v34 (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Roboto', sans-serif; font-weight: normal;">
            Roboto Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Roboto Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Roboto Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>

        <li style="font-family: 'Ubuntu', sans-serif; font-weight: normal;">
            Ubuntu Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Ubuntu Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Ubuntu Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
        <li style="font-family: 'Ubuntu Mono', sans-serif; font-weight: normal;">
            Ubuntu Mono Regular (r). The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789 <br/>
            Ubuntu Mono Regular (b). <b>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</b> <br/>
            Ubuntu Mono Regular (i). <i>The quick brown fox jumped over the lazy dog. Oh how I quickly daft over leaping jumping zebras! 01234-56789</i>
        </li>
    </ul>
</section>